apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xmangodbs.mangodb.de
  labels:
    kube-bind.io/exported: "true"
spec:
  group: mangodb.de
  names:
    kind: XMangoDB
    plural: xmangodbs
  claimNames:
    kind: MangoDB
    plural: mangodbs
  defaultCompositionRef:
    name: on-prem
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              replicas:
                type: integer
                default: 3
              version:
                type: string
                minLength: 1
                default: "4.2.6"
